import { defineConfig } from 'vite';
import { resolve } from 'node:path';
import { AREAS } from './scripts/practice-areas.data.mjs';

// One Rollup entry per page. Practice-area pages are generated by
// `npm run build:practice`, which the build script runs first.
const input = { main: resolve(__dirname, 'index.html') };
for (const area of AREAS) {
   input[area.slug] = resolve(__dirname, 'practice', area.slug, 'index.html');
}

export default defineConfig({
   build: {
      rollupOptions: { input }
   }
});
